### ISSUE TITLE
InventoryViewer: フォルダのお気に入り登録の登録場所がおかしい

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [rheniumNV/neos-util-console#17]
InventoryViewerでフォルダを開いているときに星アイコンでお気に入り登録すると、
お気に入りされる場所が正しく登録されない

![image](https://user-images.githubusercontent.com/7685946/155116146-fabf7a34-2cce-42a6-84b0-3ec2d200994a.png)

画像の上2つはフォルダからお気に入り登録したもの

- JP Tools: Essential Toolsからお気に入り登録。開くと何も表示されない
- Brushes: Essential Toolsからお気に入り登録。開くとEssential Toolsが表示される
- rhenium Public: topからインベントリリンクを貼り付けてお気に入り登録。正しく表示される。

**Comment by rheniumNV** [comment]
報告ありがとうございます！

原因が分かりました。
・ディレクトリの場合、移動時にパスと名前を結合するべきところで名前が入っていなかった
・リンクの場合、そもそもパスが全く違うため移動できなかった

ディレクトリは名前を追加すれば問題なし。
リンクの場合はRecordIdを使い、/inventory/v1/viewrではなく/inventory/v1/linkに飛ばせばよい。
しかし、お気に入りの情報にrecordTypeを入れていなかったため見分けがつかないという問題あり、悩んでいます。

さらに、ディレクトリもリンクもRecordIdがあるのでどちらもinventory/v1/linkに飛ばすという選択もありますが、そもそもlinkは一度レコード情報を取得する必要があり遅いです。

色々とごちゃごちゃになってしまったので、一度壊してお気に入り登録時にリンク先のパスの情報まで保存するように作りなおすのもありかなと考えているところでした。

**Comment by rheniumNV** [comment]
動かないままはよくないので一旦、全てlinkに飛ばして動くようにしました。
https://github.com/rheniumNV/neos-util-console/pull/21

**Comment by rheniumNV** [comment]
バグという意味では解決したのでここは閉じて、別イシューを残すことにしました。
https://github.com/rheniumNV/neos-util-console/issues/22
