### ISSUE TITLE
InventoryViewer: Neos EssentialsのリンクでEssential Toolsが開く

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [rheniumNV/neos-util-console#18]
![image](https://user-images.githubusercontent.com/7685946/155116577-25c274ee-4af9-4523-b4a1-ad7345a2598c.png)

**Comment by rheniumNV** [comment]
報告ありがとうございます！

修正しました。
https://github.com/rheniumNV/neos-util-console/pull/20
