### ISSUE TITLE
inventory-viewerで黄色のフォルダを選択すると中身が表示されない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [rheniumNV/neos-util-console#8]
# 現象
黄色のフォルダをクリックすると中身が表示されない

![image](https://user-images.githubusercontent.com/7685946/154662480-57b2f514-383e-439e-9351-0c49ddab029e.png)

オレンジ色のパブリックフォルダをクリックするとうまく表示される

![image](https://user-images.githubusercontent.com/7685946/154662965-a173e4bd-6ab9-4cdb-8f99-865e30c049bc.png)

# 推測
`U-rhenium / rhenium Public/Projects` のパス区切り文字がスラッシュ`/`になってるのが悪さしてそう

**Comment by rheniumNV** [comment]
報告ありがとうございます。

しかし、私のブラウザでは問題なく表示されました。

1枚目の画像のパスが「rhenium Public/Projects」になっているのが気になります。
「Inventory/」が抜けているため表示されていないのではないかと思いました。
しかし、通常の操作をしてそうなったのであれば問題です。再現方法を知りたいです。
この問題は黄色のフォルダを開くとき、必ず発生していますか？

![image](https://user-images.githubusercontent.com/71165146/154669211-c5226e89-32f7-41f3-9d32-ee1367fe6b91.png)
![image](https://user-images.githubusercontent.com/71165146/154669375-1bb9d1fd-3362-4975-8f7b-c74d252850cd.png)
